name: paged_datatable
description: A Flutter widget which is a paged DataTable which supports cursor pagination
<<<<<<< HEAD
version: 0.4.4
=======
version: 0.1.2
>>>>>>> 063a5f1c168eae548cb0c085faef6162da0a0631
homepage: https://github.com/TomasWeg/paged-datatable

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  intl: ^0.17.0
  stream_transform: ^2.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true

flutter_intl:
  enabled: true
  class_name: PagedDataTableLocalization 
  main_locale: en 
  arb_dir: lib/l10n 
  output_dir: lib/l10n/generated
  use_deferred_loading: false