name: paged_datatable
description: A Flutter widget which is a paged DataTable which supports cursor pagination
version: 0.1.0
homepage: https://github.com/TomasWeg/paged-datatable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  intl: ^0.17.0
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0