name: paged_datatable
description: A brand new way of creating paginated DataTables in Flutter with sorting and filters
version: 1.4.4
homepage: https://github.com/tomasweigenast/paged-datatable

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  collection: ^1.17.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  two_dimensional_scrollables: ^0.1.2

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.1
  intl_utils: ^2.8.5
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  generate: true

flutter_intl:
  enabled: true
  class_name: PagedDataTableLocalization
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  use_deferred_loading: false
